---
units:
- name: cardinal
  ports:
    - default->4455/https
  description: >
    Hello, World HTTP server

plans:
- name: default
  instances:
    desired: 1
  workflow:
    kind: pulsar
    blueprint: example@HEAD

namespaces:
- name: dev
  units:
  - ref: cardinal
    plans:
    - default

datacenters:
  only:
  - us-east-1
